// <auto-generated />
using System;
using ExamVault.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamVault.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424190458_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("AccionAuditada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("IpOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAuditoria");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estrellas")
                        .HasColumnType("integer");

                    b.Property<int>("IdSesion")
                        .HasColumnType("integer");

                    b.HasKey("IdCalificacion");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Descarga", b =>
                {
                    b.Property<int>("IdDescarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescarga"));

                    b.Property<DateTime>("FechaDescarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdDescarga");

                    b.ToTable("Descargas");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Institucion", b =>
                {
                    b.Property<int>("IdInstituciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInstituciones"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominioCorreo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInstituciones");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMateria");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaModeracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.Property<int?>("IdModerador")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("TamanoBytes")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMaterial");

                    b.HasIndex("IdModerador");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Monitor", b =>
                {
                    b.Property<int>("IdMonitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMonitor"));

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMonitor");

                    b.ToTable("Monitores");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.MonitorMateria", b =>
                {
                    b.Property<int>("IdMonitor")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("IdMonitor", "IdMateria");

                    b.ToTable("MonitoresMaterias");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("IdPlanes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanes"));

                    b.Property<int>("LimiteAlmacenamiento")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteEstudiantes")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDelPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric");

                    b.HasKey("IdPlanes");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("IdPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrograma"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("NombrePrograma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPrograma");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.ProgramaMateria", b =>
                {
                    b.Property<int>("IdPrograma")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("IdPrograma", "IdMateria");

                    b.ToTable("ProgramasMaterias");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.SesionMonitoria", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSesion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMonitor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SolicitadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("IdSesion");

                    b.ToTable("SesionesMonitores");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Suscripcion", b =>
                {
                    b.Property<int>("IdSuscripciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuscripciones"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlanes")
                        .HasColumnType("integer");

                    b.HasKey("IdSuscripciones");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("ExamVault.Api.Domain.Entities.Material", b =>
                {
                    b.HasOne("ExamVault.Api.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdModerador");

                    b.HasOne("ExamVault.Api.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
