// <auto-generated />
using System;
using ExamVault.Api.Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamVault.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517214220_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("AccionAuditada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("IpOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estrellas")
                        .HasColumnType("integer");

                    b.Property<int>("IdSesion")
                        .HasColumnType("integer");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdSesion");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Descarga", b =>
                {
                    b.Property<int>("IdDescarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescarga"));

                    b.Property<DateTime>("FechaDescarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdDescarga");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Descargas");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Institucion", b =>
                {
                    b.Property<int>("IdInstituciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInstituciones"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominioCorreo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInstituciones");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdInstituciones");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaModeracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.Property<int?>("IdModerador")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoMaterial")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("TamanoBytes")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdMaterial");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdModerador");

                    b.HasIndex("IdTipoMaterial");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Monitor", b =>
                {
                    b.Property<int>("IdMonitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMonitor"));

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMonitor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Monitores");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.MonitorMateria", b =>
                {
                    b.Property<int>("IdMonitor")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("IdMonitor", "IdMateria");

                    b.ToTable("MonitoresMaterias");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Permisos", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreTabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permiso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.PermisosAtributos", b =>
                {
                    b.Property<int>("IdPermisoAtributo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermisoAtributo"));

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreAtributo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permiso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPermisoAtributo");

                    b.HasIndex("IdRol");

                    b.ToTable("PermisosAtributos", (string)null);
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Plan", b =>
                {
                    b.Property<int>("IdPlanes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanes"));

                    b.Property<int>("LimiteAlmacenamiento")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteEstudiantes")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDelPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric");

                    b.HasKey("IdPlanes");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Programa", b =>
                {
                    b.Property<int>("IdPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrograma"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("NombrePrograma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPrograma");

                    b.HasIndex("IdInstituciones");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.ProgramaMateria", b =>
                {
                    b.Property<int>("IdPrograma")
                        .HasColumnType("integer");

                    b.Property<int>("IdMateria")
                        .HasColumnType("integer");

                    b.HasKey("IdPrograma", "IdMateria");

                    b.ToTable("ProgramasMaterias");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.SesionMonitoria", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSesion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMonitor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SolicitadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdMonitor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SesionesMonitores");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Suscripcion", b =>
                {
                    b.Property<int>("IdSuscripciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuscripciones"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlanes")
                        .HasColumnType("integer");

                    b.HasKey("IdSuscripciones");

                    b.HasIndex("IdInstituciones");

                    b.HasIndex("IdPlanes");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.TipoMaterial", b =>
                {
                    b.Property<int>("IdTipoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoMaterial"));

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTipoMaterial");

                    b.ToTable("TipoMaterial");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("IdInstituciones")
                        .HasColumnType("integer");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdInstituciones");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Auditoria", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Calificacion", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.SesionMonitoria", null)
                        .WithMany()
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Descarga", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.TipoMaterial", null)
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Materia", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Institucion", null)
                        .WithMany()
                        .HasForeignKey("IdInstituciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Material", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Materia", null)
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdModerador");

                    b.HasOne("ExamVault.Api.Dominio.Entidades.TipoMaterial", null)
                        .WithMany()
                        .HasForeignKey("IdTipoMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Monitor", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Permisos", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PERMISOS_ROLES_FK");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.PermisosAtributos", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PERMISOS_ATRIBUTOS_ROLES_FK");
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Programa", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Institucion", null)
                        .WithMany()
                        .HasForeignKey("IdInstituciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.SesionMonitoria", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Monitor", null)
                        .WithMany()
                        .HasForeignKey("IdMonitor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamVault.Api.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Suscripcion", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Institucion", null)
                        .WithMany()
                        .HasForeignKey("IdInstituciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamVault.Api.Dominio.Entidades.Plan", null)
                        .WithMany()
                        .HasForeignKey("IdPlanes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamVault.Api.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("ExamVault.Api.Dominio.Entidades.Institucion", null)
                        .WithMany()
                        .HasForeignKey("IdInstituciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
